### ISSUE TITLE
Add gitignore and remove useless files

### ISSUE THREAD

**Issue by seia-soto** [Chanmi-Kim/react-study#71]
**[Context]**

- Removing `node_modules` from the repository is required as `node_modules` is a reinstallable dependency

**[Problem or idea]**

- `node_modules` is not required to upload to git and consumes a lot of disk spaces.

**[Solution or next step]**

- Add `.gitignore` file and add some frequently used patterns
- Remove `node_modules` and possible useless files from the repository

----

**[상황]**

- `node_modules`는 올리지 않아도 재설치 가능하여 저장소에서 `node_modules`를 제거해야 합니다.

**[문제점]**

- `node_modules`는 깃에 업로드할 필요가 없으며 많은 저장 공간을 사용합니다.

**[해결방안]**

- `.gitignore` 추가 및 자주 사용되는 패턴 추가
- `node_modules` 및 패턴 삭제

**Comment by Yian-Kim** [comment]
```git
$ npx gitignore node
```

@seia-soto, please check.
I solved it by referring to the command.

---

@seia-soto님, 확인 부탁드립니다.
명령어 참고해서 해결했습니다.

**Comment by Yian-Kim** [comment]
Checked it.
